[package]
name = "mneme_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
headless_chrome = "1.0.21"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = "1.49.0"
